server:
  port: 8003
management:
  endpoints:
    web:
      exposure:
        include: "*" # 开启全部的 endpoints
#  server:
#    port: 8004
#    servlet:
#      context-path: /monitor
info:
 app:
   name: springboot-actuator
   version: v1.0.0

